### ISSUE TITLE
Tests don't make sense

### ISSUE THREAD

**Issue by jldodds** [cjerdonek/open-rcv-tests#1]
We are interested in using these tests/this format for input to our software, however, we are having trouble understanding the existing tests. For example, in the following snippet, I am having trouble how the totals, elected, and ballots all match up. Could you explain?

``` JSON
            "input": {
                "_meta": {
                    "id": "7e478420",
                    "index": 1,
                    "name": "Simple winner in first round.",
                    "rule_sets": [
                        "irv"
                    ]
                },
                "ballots": [
                    "1 1",
                    "2 2"
                ],
                "candidate_count": 2
            },
            "output": {
                "rounds": [
                    {
                        "elected": [
                            "Bob"
                        ],
                        "totals": {
                            "Ann": 1,
                            "Bob": 2
                        }
                    }
```

**Comment by cjerdonek** [comment]
Thanks for your interest in this, and sorry it's not documented better.  I had to put it down at the time for reasons of time, but it's something I'd like to return to because I think test cases like these are enormously important.

IIRC, the above can be explained as follows.  For readability, the candidates are represented using string names instead of numbers.  It is always in alphabetical order with the first letter corresponding to the candidate ID, so A for 1, B for 2, etc.  In this case, with `candidate_count` two, there are Ann and Bob.

The ballots are represented using the "packed" form (a simple form of compression), which means the first number for a ballot corresponds to the quantity of that ballot.  The numbers after the first number are the choices of the voter at each ranking, in order.  (I believe the list of ballots is similar to the BLT format, which I believe you are familiar with.)  So the two ballots above each have only one ranking (and the second ballot appears twice).

In the "output" section, "rounds" is an array, with the elements sequentially corresponding to round 1, round 2, etc.  So in the above case, there was one round.  In that round, Bob was elected with vote totals 1 and 2 for Ann and Bob, respectively.  So what's good about a test case format like this is that it lets you test the finer-grained output of round-by-round vote totals instead of something coarser like simply the winner, or the final round vote totals.

I also had plans to incorporate tie-break data into the input (for when the data results in ties), but I'm not sure if I got to it.

**Comment by cjerdonek** [comment]
Also, see the constants.json file for the name conventions used for different candidate IDs.

**Comment by jldodds** [comment]
Thanks for the clarification! I wasn't understanding the "packed" form

It looks like you started on tie break but didn't finish with the outputs. My real sticking point was the form of the input though. Thanks!

**Comment by pchickey** [comment]
So, in test 6, with ballots `[ "3", "2 2", "1 3" ]`, there are 3 empty ballots, 2 ballots voting only for Bob, and 1 ballot voting only for Carol?

**Comment by pchickey** [comment]
Two more things:

For a given object in the `test_cases` array, the `_meta.index` value does not always match the `input._meta.index` value. I had to just pick one of the two to be a canonical way to refer to which test it was, so I picked `input._meta.index`, since there was more useful information in that `_meta` object. Is there a reason these are sometimes different? If not, will you accept a pull request with these fixed up to match?

Second - some output objects do not have an `elected` field, even though the `totals` indicate a winner. Is there a reason this was left out? If not, will you accept a pull request with `elected` fields added where they are missing?

**Comment by cjerdonek** [comment]
> So, in test 6

@pchickey Yes. I added some more degenerate test cases to start with.

**Comment by cjerdonek** [comment]
> Is there a reason these are sometimes different?

~~No, they should be the same.~~ I think my original thinking was that the string ID should be used as the "permalink," since the index may change from commit to commit (I believe the index was again for readability since it is easier to reference within test output, etc).

The absence of "elected" is probably just because I was in the middle of things when putting this down.  Sure, PR's welcome.

Note that one issue I remember starting to work on was separating "input" from "output."  Basically, I was starting to see that it would be useful to have the same input data be used across more than one tally variation.  I didn't want to have all tally variations be accumulating in the same file since it wouldn't scale well.  IIRC, the "index" would be used to link across files, etc, but not meant to be used to referenced outside the context of a particular commit / SHA.

**Comment by cjerdonek** [comment]
> For a given object in the test_cases array, the _meta.index value does not always match the input._meta.index value.

Okay, so I took a look and remember why this is now.  The file `test_prep/contests.json` has all of the input data, which can be used to generate self-contained test cases.  Each input has its own "id" and increasing "index" value.

The file `tests/irv.json` is a collection of self-contained test cases, each of which includes _both_ input data and expected output.  Each test case has its own index, which can be different from the index of the input it uses.  The two numbers start diverging at test-case index 8 because there the same input is used to generate two different two cases (one without batch elimination and one with batch elimination).

As I said above, I was in the process of working through a good format when I put this down.  One of the driving goals I had was to make _running_ the tests as easy as possible (possibly at the expense of things like DRY, etc).  This led me to the idea of making each test-case self-contained.  As a consequence, you sacrifice brevity because the same test input could be repeated possibly multiple times throughout the test suite.  This explains the "test_prep" directory.  I was planning on keeping the DRY data to generate the tests in that "prep" directory, and then generating the test cases from that for consumption at the top level.  Does that make sense?

Summary: test consumers should only need to look at the top-level files.  Repo maintainers would use the "prep" directory to maintain the tests and auto-generate the top-level files from that data.
